Feature/vis by turbine
NREL/floris pull request #418
Opened 2022-04-12 19:26 UTC by paulf81

Not ready to be merged

**Feature or improvement description**
Some wake models (cc, turbopark) are not yet set up to enable visualization of the horizontal flowfield.  However this visualization can be useful in understanding, sanity checking etc.  This pull request provides a function to calculate the flowfield, through a slower process, of sweeping an extra turbine around the domain in a nested for loop and extracting the u-velocity at hub height

Pull request comes with demo example to show the new method:
calculate_horizontal_plane_with_turbines

Which at at upper most level behaves much like calculate_horizontal_plane except height can not be freely specified.  Results in plot:

![image](https://user-images.githubusercontent.com/6117702/163038316-c19adf90-e63c-4fc1-80a0-2e0710ab0176.png)

**Related issue, if one exists**
Issue #355

2022-04-14 17:01 UTC, Bartdoekemeijer commented
Hi @paulf81. I like this idea of having an artificial turbine in FLORIS function as a probe. I ran the example and saw it run very slowly on my machine. I think this is because of the overhead coming from reinitializing the FLORIS object for every measurement (in the example, we reinitialize FLORIS 600 times). Simply reinitializing floris 600 times on my laptop took `222.75 s`.

Here's an idea based on yours, but circumventing the reinitialize issue. What if we add one turbine for every probe measurement? So if we want to calculate a grid of 40 x 15 wind speeds, we add 600 turbines to the farm. We make these turbines of the `turbine_type=probe`, give them a rotor diameter of `-1`, and a thrust curve of zeros. We can change that probe's location and hub height to specify the (x, y, z) coordinate of every measurement. Then, in `solver.py`, at the very start of the loop: https://github.com/NREL/floris/blob/a23241bb9e45078e36a4662d48c9d3fe0c3316e4/floris/simulation/solver.py#L383

we can add
```
if farm.rotor_diameters[i] < 0.001:
    continue
````

so that these probes have zero effect on the flow field. This would also enable users to handpick measurement locations, rather than always being forced to a grid. It would also resolve the issue with requiring a separate flowfield solver function, like `full_flow_cc_solver`.

@bayc @rafmudaf Feel free to let me know if this is a horrible idea. I understand it would go against some principles in how you designed the FLORIS model.

2022-04-14 19:59 UTC, paulf81 commented
I think that's really brilliant @Bartdoekemeijer , I really like it!

2022-04-14 21:04 UTC, Bartdoekemeijer commented
Okay I just opened a pull request here: https://github.com/paulf81/floris/pull/12

It's a very primitive version of what the turbines-as-probes method that I was trying to explain. It's a little iffy but it mostly works. Try running the example code that I added and see what you think.

2023-02-01 20:42 UTC, rafmudaf commented
TODO:
- [ ] Remove example
- [ ] Move plotting function to `floris.tools.visualization`

2023-02-06 22:33 UTC, bayc commented on floris/tools/visualization.py
> +                fi.calculate_wake(yaw_angles=yaw_angles)
I believe we need to down select the yaw angle needed here for the individual turbine.

2023-02-06 23:04 UTC, rafmudaf requested changes

2023-02-06 23:04 UTC, rafmudaf commented on floris/tools/visualization.py
> +        # # Store the current state for reinitialization
Is this important to keep?

2023-02-06 23:38 UTC, paulf81 commented on floris/tools/visualization.py
> +                FLORIS object.
Fixed

2023-02-06 23:38 UTC, paulf81 commented on floris/tools/visualization.py
> +            height (float): Height of cut plane. Defaults to Hub-height.
Deleted

2023-02-06 23:39 UTC, paulf81 commented on floris/tools/visualization.py
> +            yaw_angles ((np.ndarray), optional): Wind speed for visualization
Fixed

2023-02-06 23:51 UTC, rafmudaf approved these changes

2023-02-07 18:56 UTC, rafmudaf commented
This PR depends on #569

2023-02-07 20:56 UTC, merged